providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11.3"
BE_ENV = 'prod'

[phases.custom_install]
cmds = ["pip install git+https://github.com/benoitc/gunicorn.git"]
dependsOn = ['install']

[phases.test]
cmds = ["export BE_ENV=test", "coverage run -m pytest || exit -1", "coverage report", "export BE_ENV=prod"]
dependsOn = ['custom_install']

[start]
cmd = "gunicorn --worker-class eventlet -b 0.0.0.0:8000 --workers 1 --threads 100 main_run:app"
