"""is_full room attribute

Revision ID: 37177004bc34
Revises: 2c74fcb63719
Create Date: 2023-09-20 21:02:06.479870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37177004bc34'
down_revision = '2c74fcb63719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_full', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('is_full')

    # ### end Alembic commands ###
